# The number of functions
sample_number: 400

# The file that stores the output information
result_file: "invokeResult.csv"

# The total time for testing in seconds
total_run_time: 1800
#total_run_time: 30

# If true, RealWorldAppEmulation.py will automatically generate random samples
# We suggest that generate the samples manually or automatically generate samples only once
manual_sample_generation: True
